// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/get-wallet-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-wallet-summary.ts
var COINS_PER_RUPEE = 100;
var get_wallet_summary_default = defineTool({
  name: "get_wallet_summary",
  title: "Get wallet summary",
  description: "Get the signed-in user's XD Coin balances, total earnings, ads watched and referral stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_profiles").select(
      "display_name, withdrawable_balance, non_withdrawable_balance, total_earnings, weekly_earnings, ads_watched, referrals_count, referral_code"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }], isError: true };
    const summary = {
      ...data,
      withdrawable_inr: Number((data.withdrawable_balance / COINS_PER_RUPEE).toFixed(2)),
      minimum_withdrawal_inr: 50
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's recent XD Coin transactions (earnings, bonuses, redemptions).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("How many transactions to return."),
    transaction_type: z.string().trim().min(1).optional().describe("Optional filter, e.g. 'ad_reward', 'daily_bonus', 'withdrawal'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, transaction_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transactions").select("id, amount, transaction_type, description, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (transaction_type) query = query.eq("transaction_type", transaction_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-achievements.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
var list_achievements_default = defineTool3({
  name: "list_achievements",
  title: "List achievements",
  description: "List the badges the signed-in user has unlocked in XD Rewards.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_badges").select("badge_key, badge_name, badge_description, earned_at").eq("user_id", ctx.getUserId()).order("earned_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { badges: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool4({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the current XD Rewards weekly leaderboard ranking.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("How many ranks to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_public_leaderboard", {
      limit_count: limit ?? 10
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leaderboard: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-withdrawals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var COINS_PER_RUPEE2 = 100;
var PAYOUT_WINDOW_HOURS = 48;
function estimatePayout(status, createdAt, processedAt) {
  if (status === "completed") {
    return { estimated_payout: null, note: processedAt ? `Paid on ${processedAt}` : "Paid" };
  }
  if (status === "rejected" || status === "cancelled") {
    return { estimated_payout: null, note: "Request was not approved" };
  }
  const eta = new Date(new Date(createdAt).getTime() + PAYOUT_WINDOW_HOURS * 36e5);
  const overdue = eta.getTime() < Date.now();
  return {
    estimated_payout: eta.toISOString(),
    note: overdue ? "Under manual verification \u2014 slightly past the usual 48 hour window" : "Processed within 48 hours after manual verification"
  };
}
var list_withdrawals_default = defineTool5({
  name: "list_withdrawals",
  title: "List withdrawal requests",
  description: "List the signed-in user's latest withdrawal / redemption requests with their status and estimated payout time.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("How many requests to return."),
    status: z3.string().trim().min(1).optional().describe("Optional status filter, e.g. 'pending' or 'completed'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("gift_card_purchases").select(
      "id, amount_paid, status, created_at, processed_at, email, product:gift_card_products(name, brand, denomination)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const withdrawals = (data ?? []).map((row) => {
      const timing = estimatePayout(row.status, row.created_at, row.processed_at);
      return {
        id: row.id,
        reward: row.product?.name ?? "Reward",
        brand: row.product?.brand ?? null,
        amount_inr: Number(row.amount_paid),
        amount_xd_coins: Math.round(Number(row.amount_paid) * COINS_PER_RUPEE2),
        status: row.status,
        requested_at: row.created_at,
        processed_at: row.processed_at,
        payout_email: row.email ?? null,
        ...timing
      };
    });
    const summary = withdrawals.length === 0 ? "No withdrawal requests found." : withdrawals.map(
      (w) => `${w.reward} \u2014 \u20B9${w.amount_inr} (${w.amount_xd_coins} XD Coins) \xB7 ${w.status} \xB7 requested ${w.requested_at}` + (w.estimated_payout ? ` \xB7 estimated payout by ${w.estimated_payout}` : "") + ` \xB7 ${w.note}`
    ).join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { withdrawals, minimum_withdrawal_inr: 50, payout_window_hours: PAYOUT_WINDOW_HOURS }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aqltdrlkrsreprqkbvvo";
var mcp_default = defineMcp({
  name: "xd-rewards-back",
  title: "XD Rewards back \u{1F3C6}",
  version: "0.1.0",
  instructions: "Tools for XD Rewards, an entertainment rewards platform where users earn XD Coins (1000 XD Coins = \u20B910 INR). Use `get_wallet_summary` for balances, `list_transactions` for earning history, `list_withdrawals` for withdrawal/redemption requests with status and estimated payout time, `list_achievements` for unlocked badges and `get_leaderboard` for the weekly ranking. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_wallet_summary_default, list_transactions_default, list_withdrawals_default, list_achievements_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
