REVOKE EXECUTE ON FUNCTION public.admin_lift_ban(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_unlink_device(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_referral_code(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.approve_social_task(uuid, boolean, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_and_award_badges(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_and_register_device(text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_daily_reward(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_public_leaderboard(integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_current_user_banned() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.purchase_gift_card(uuid, uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.record_ad_completion(uuid, integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.redeem_gift_card(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.spin_wheel(uuid) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.admin_lift_ban(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_unlink_device(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_referral_code(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.approve_social_task(uuid, boolean, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_and_award_badges(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_and_register_device(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_daily_reward(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_public_leaderboard(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_current_user_banned() TO service_role;
GRANT EXECUTE ON FUNCTION public.purchase_gift_card(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_ad_completion(uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.redeem_gift_card(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.spin_wheel(uuid) TO service_role;